### ISSUE TITLE
Alternative configs

### ISSUE THREAD

**Issue by pett-j** [OpenStickCommunity/Hardware#11]
As discussed with Train, I am raising this so he can think if it's worth offereing alternative configs in the repo.

Examples:
 - "Basic" config which has all the needed SMD components soldered, but with just the 20pin and 4pin headers populated
 - Alternative "basic" config would be the same as the above but instead have just the screw terminals populated

**Comment by TheTrainGoes** [comment]
All of these are possible.  I am thinking about the following:

- Depopulated of all headers and connectors
- Depopulated of all headers except the 20pin and 4pin
- Depopulated of all headers except the screw terminal row

This can be done quickly by just unchecking some of the headers and connectors when ordering, but a modified BoM and PnP file can also be made for it.
