### ISSUE TITLE
Missing compatible RGB LED link in README

### ISSUE THREAD

**Issue by mlbaquerizo** [OpenStickCommunity/Hardware#31]
Looks like there should be a link where the word "HERE" is:

https://github.com/OpenStickCommunity/Hardware/blob/47f64a494358614ff2270e9a3b7d16877fe86c7e/RP2040%20Advanced%20Breakout%20Board/README.md?plain=1#L42

**Comment by TheTrainGoes** [comment]
Thank you for pointing this out @mlbaquerizo ,

I have updated it to generically point to WS2812B and SK6812 LEDs.
