### ISSUE TITLE
`How to order a board` JLCPCB order issue 

### ISSUE THREAD

**Issue by motoishmz** [OpenStickCommunity/Hardware#38]
Hi, thanks for sharing this great repo! I've started to make my own first controller, and I'm trying to order the board from JLCPCB. I've followed the steps in [How to order a board](https://github.com/OpenStickCommunity/Hardware/blob/main/RP2040%20Advanced%20Breakout%20Board/README.md#how-to-order-a-board) on RP2040 Advanced Breakout Board. But I've encountered some issues when I tried to order the board from JLCPCB. I'm not sure if I've made some mistakes, or the website has changed. Could you please help me to check it?

---

## 1. PCB Assenmbly > PCBA Type
I Couldn't select `Economic`. The web page says the PCB spec I've choose is not supported for Economic PCBA.
<img width="504" alt="image" src="https://github.com/OpenStickCommunity/Hardware/assets/676599/42194509-9b82-4b82-88ee-5fd0e9f8668e">

### UPDATE
I realized that this issue happens when you select the yellow color PCB. I chose the another color, then the Economic button became enabled.

---

## 2. PCB Assenmbly > Tooling holes
Maybe the `Tooling holes` is replaced by `Edge Rails/Fiducials`?
<img width="766" alt="image" src="https://github.com/OpenStickCommunity/Hardware/assets/676599/905c28a9-6817-486c-a843-bcd96714f640">

I chose `Added by Customer`, then I clicked `NEXT`, but the alert appeared
<img width="666" alt="image" src="https://github.com/OpenStickCommunity/Hardware/assets/676599/f3b4cee9-327b-42b2-b201-eda0b14a9502">

I clicked `JLCPCB helps....`, the website automaticaly changed the PCB size to 71.31mm*96.3mm, and the `Edge Rails/Fiducials` also changed to `Added by JLCPCB`. 

---

## 3. Bill of Materials
I've uploaded the BOM / CPL file, but the web site says there are some missing parts.

<img width="768" alt="image" src="https://github.com/OpenStickCommunity/Hardware/assets/676599/7b499d74-72d0-4b11-a0d7-7a21a00a6a88">

---

Thanks for your help.

**Comment by TheTrainGoes** [comment]
Hi @motoishmz,

JLC has recently updated their order process and the guide may be out of date.  

How many boards did you attempt to order?

**Comment by motoishmz** [comment]
@TheTrainGoes Thanks for your reply. I attempt to order five boards - the minimum Qty.

**Comment by TheTrainGoes** [comment]
Hey @motoishmz I just checked this out.  Looks like yellow boards are not supported for economic assembly currently.  JLC changes these things from time to time.  The H3 and H4 errors are from the the two optional header rows for the debugging pins and the USB direct connector.  These can be skipped.

For `tooling holes` select the `added by customer` option.

**Comment by motoishmz** [comment]
@TheTrainGoes Thank you for your time, I appreciate your help.

`1. PCB Assenmbly > PCBA Type`: Okay, I'm going to choose not yellow but the another color.

`2. PCB Assenmbly > Tooling holes`: When I select "added by customer" I have to change the PCB size to the required size `71.31mm*96.3mm` manualy. Is it correct?

`3. Bill of Materials`: I'm going to ignore this error, and click `Continue`

**Comment by motoishmz** [comment]
> 2. PCB Assenmbly > Tooling holes: When I select "added by customer" I have to change the PCB size to the required size 71.31mm*96.3mm manualy. Is it correct?

This `PCB size requirement` alert didn`t appeard when I chose the white color board. Problem solved, thanks @TheTrainGoes !
