### ISSUE TITLE
Remove prerelease firmware from repo

### ISSUE THREAD

**Issue by satchow** [OpenStickCommunity/Hardware#60]

**Comment by Fortinbra** [comment]
Do you have more information about this?

**Comment by satchow** [comment]
Train asked me on Discord to create this issue.

**Comment by Fortinbra** [comment]
Oh, my apologies. I just found out about that.

**Comment by InfraredAces** [comment]
[Context from Discord](https://discord.com/channels/1049366310389289001/1133386024114987088/1165394669887295488)

**Comment by TheTrainGoes** [comment]
Removed pre-release firmware and pointed to proper firmware.
