### ISSUE TITLE
Suggestion to increase clarity regarding board features.

### ISSUE THREAD

**Issue by ForeverExe** [OpenStickCommunity/Hardware#69]
**For context:** 
I recently bought an Advanced Breakout Board (nothing wrong with it, great product by the way), there were some features that I didn't knew how they work and there were no guide coming with the board. So today I've searched on the Repo's documentation and found what I was looking for, in the middle of a wall of text.

So I would propose to reorganize the Board Design Choices section a little to help finding faster the different features of the board.

_I want to anticipate that I'm writing this with focus on the people that has little to no experience in building peripherals or electronics in general and just wants to look for what they want in little time and go straight mounting._ 

Link to [User Guide section](#user-guide)

# Repo Section
**_On the repo's documentation I would suggest to add third level headings and divide them for connector types and also adding a little list with links to the sections_**

## Summary

- [JSTs for OLED, RGB and Harness](#jsts)
- [Screw Terminals](#screw-terminals)
- [X Pin connectors](#x-pin-connectors)
- [Micro Switches and Buttons](#micro-switches-and-micro-buttons)
- [USB Ports](#usb-ports)
- [Pin Headers](#pin-headers)

# Board Design Choices
The Brook form factor was chosen due to its compatibility with a number of existing enclosures and holders.

### JSTs
- A 4pin (1x4pin) JST 2.00mm connector labeled expansion can be found on the left side that allows for either a compatible [...]

- A 3pin (1x3pin) JST 2.00mm connector labeled RGB LED can be found on the left side [...]

- A 4pin (1x4pin) JST 2.00mm connector is located beside the 20pin connector [...]

### Screw Terminals
- A 3pin (1x3pin) 3.81mm screw terminal row labeled toggle [...]

- A 10pin (1x10pin) 3.81mm screw terminal row labeled optional pins can be found at the bottom right of the board. [...]

- A 2pin (1x2pin) 3.81mm screw terminal row labeled 5v [...]

- A 20pin (1x20pin) 3.81mm screw terminal row can be found along the top of the board [...]

### X Pin Connectors
- A 20pin (2x10pin) 2.54mm connector is located in the bottom left of the board, [...]

### Micro Switches and Micro Buttons
- _**"USB<->OPTION" SMD Switch**_: A SMD switch labeled with both the USB and OPTION positions can be found on the board above Option 3 [...]

- _**"LED<->GPIO25" SMD Switch**_: a SMD switch labeled with both the LED and GPIO25 positions can be found on the board above the 4-pin harness connector. [...]

- A **BootSel Button**, which can be held on plug-in to enter BootSel mode which is used to flash the device with firmware.
- A **Reset Button**, which can be pressed to reset the device.
- A **Web-Config Button**, which can be held while plugging in to go to web-config mode. [...]

### USB Ports
- A USB-C port can be found on the right side of the board. [...]
- A female USB A port [...]

### Pin Headers
- A 3pin (1x3pin) 2.54mm header area labeled debug can be found near the middle of the board. [...]
- A 5pin (1x5pin) 2.54mm header area labeled USB direct can be found near the right of the board. [...]

# User Guide
**_Regarding the info card, I think a brief version of what is above should be fine for having a fair understanding of the board._**

So in addition to the already existing pages, I would do something like this for the most important parts (I would not do that for the pin headers for example) and add a QR code containing the link to the board features section:

![mockup](https://github.com/OpenStickCommunity/Hardware/assets/17835568/e167ef50-cfe8-4b7a-9506-a18b73740f99)

**Comment by TheTrainGoes** [comment]
Hi @ForeverExe ,

Apologies on taking so long to look at this.  

The repo is designed more for makers than general consumers.  Now that the ABB v5.6 is likely in its last iteration I will be doing work to make some better customer facing material where this stuff can be addressed.
