### ISSUE TITLE
Zip file for OSM STLs?

### ISSUE THREAD

**Issue by rdmcintee** [OpenStickCommunity/Hardware#89]
Haven't downloaded bulk files from git before so this may be my ignorance but is there a way to bulk download all of the STLs for the OSM?

**Comment by TheTrainGoes** [comment]
Hi @rdmcintee ,

If you are just navigating the web interface then I am not aware of a way to bulk download STLs. 

Most people will have the repo cloned via various methods which will bring all files with it.

I do not have any intentions of adding ZIP files at this time.
