### ISSUE TITLE
Issue with Missing Data for PCB Assembly

### ISSUE THREAD

**Issue by sebastian4j** [OpenStickCommunity/Hardware#90]
Hello,

I am trying to create a PCB using the files from this repository. However, I encountered the following error: "The below parts won't be assembled due to data missing: H3, H4 designators don't exist in the BOM file."

It seems that the designators H3 and H4 are missing in the BOM file. Could you please advise on how to resolve this issue? Are there updated files available or any additional steps I need to take?

Thank you for your assistance.

Best regards,
Sebastián Ávila A.
![Captura de pantalla 2024-07-17 165844](https://github.com/user-attachments/assets/9e82003d-057b-480e-9cd6-50a3f542884f)

**Comment by pett-j** [comment]
If you are referring to the v5.6 ABB, please look at note 6 on the readme.

**Comment by sebastian4j** [comment]
> If you are referring to the v5.6 ABB, please look at note 6 on the readme.

Thank you very much, it was my mistake 😅. I really appreciate your help!
